// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module design_1_v_tpg_0_0_MultiPixStream2AXIvi (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        strmPix_V_val_0_V_dout,
        strmPix_V_val_0_V_empty_n,
        strmPix_V_val_0_V_read,
        strmPix_V_val_1_V_dout,
        strmPix_V_val_1_V_empty_n,
        strmPix_V_val_1_V_read,
        strmPix_V_val_2_V_dout,
        strmPix_V_val_2_V_empty_n,
        strmPix_V_val_2_V_read,
        m_axis_video_TDATA,
        m_axis_video_TVALID,
        m_axis_video_TREADY,
        m_axis_video_TKEEP,
        m_axis_video_TSTRB,
        m_axis_video_TUSER,
        m_axis_video_TLAST,
        m_axis_video_TID,
        m_axis_video_TDEST,
        Height,
        WidthOut,
        colorFormat
);


input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] strmPix_V_val_0_V_dout;
input   strmPix_V_val_0_V_empty_n;
output   strmPix_V_val_0_V_read;
input  [7:0] strmPix_V_val_1_V_dout;
input   strmPix_V_val_1_V_empty_n;
output   strmPix_V_val_1_V_read;
input  [7:0] strmPix_V_val_2_V_dout;
input   strmPix_V_val_2_V_empty_n;
output   strmPix_V_val_2_V_read;
output  [23:0] m_axis_video_TDATA;
output   m_axis_video_TVALID;
input   m_axis_video_TREADY;
output  [2:0] m_axis_video_TKEEP;
output  [2:0] m_axis_video_TSTRB;
output  [0:0] m_axis_video_TUSER;
output  [0:0] m_axis_video_TLAST;
output  [0:0] m_axis_video_TID;
output  [0:0] m_axis_video_TDEST;
input  [15:0] Height;
input  [15:0] WidthOut;
input  [7:0] colorFormat;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire   [0:0] ap_CS_fsm_state1;
reg   [23:0] AXI_video_strm_V_data_V_1_data_out;
reg    AXI_video_strm_V_data_V_1_vld_in;
wire    AXI_video_strm_V_data_V_1_vld_out;
wire    AXI_video_strm_V_data_V_1_ack_in;
wire    AXI_video_strm_V_data_V_1_ack_out;
reg   [23:0] AXI_video_strm_V_data_V_1_payload_A;
reg   [23:0] AXI_video_strm_V_data_V_1_payload_B;
reg    AXI_video_strm_V_data_V_1_sel_rd;
reg    AXI_video_strm_V_data_V_1_sel_wr;
wire    AXI_video_strm_V_data_V_1_sel;
wire    AXI_video_strm_V_data_V_1_load_A;
wire    AXI_video_strm_V_data_V_1_load_B;
reg   [1:0] AXI_video_strm_V_data_V_1_state;
wire    AXI_video_strm_V_data_V_1_state_cmp_full;
wire   [2:0] AXI_video_strm_V_keep_V_1_data_out;
reg    AXI_video_strm_V_keep_V_1_vld_in;
wire    AXI_video_strm_V_keep_V_1_vld_out;
wire    AXI_video_strm_V_keep_V_1_ack_in;
wire    AXI_video_strm_V_keep_V_1_ack_out;
reg    AXI_video_strm_V_keep_V_1_sel_rd;
wire    AXI_video_strm_V_keep_V_1_sel;
reg   [1:0] AXI_video_strm_V_keep_V_1_state;
wire   [2:0] AXI_video_strm_V_strb_V_1_data_out;
reg    AXI_video_strm_V_strb_V_1_vld_in;
wire    AXI_video_strm_V_strb_V_1_vld_out;
wire    AXI_video_strm_V_strb_V_1_ack_in;
wire    AXI_video_strm_V_strb_V_1_ack_out;
reg    AXI_video_strm_V_strb_V_1_sel_rd;
wire    AXI_video_strm_V_strb_V_1_sel;
reg   [1:0] AXI_video_strm_V_strb_V_1_state;
reg   [0:0] AXI_video_strm_V_user_V_1_data_out;
reg    AXI_video_strm_V_user_V_1_vld_in;
wire    AXI_video_strm_V_user_V_1_vld_out;
wire    AXI_video_strm_V_user_V_1_ack_in;
wire    AXI_video_strm_V_user_V_1_ack_out;
reg   [0:0] AXI_video_strm_V_user_V_1_payload_A;
reg   [0:0] AXI_video_strm_V_user_V_1_payload_B;
reg    AXI_video_strm_V_user_V_1_sel_rd;
reg    AXI_video_strm_V_user_V_1_sel_wr;
wire    AXI_video_strm_V_user_V_1_sel;
wire    AXI_video_strm_V_user_V_1_load_A;
wire    AXI_video_strm_V_user_V_1_load_B;
reg   [1:0] AXI_video_strm_V_user_V_1_state;
wire    AXI_video_strm_V_user_V_1_state_cmp_full;
reg   [0:0] AXI_video_strm_V_last_V_1_data_out;
reg    AXI_video_strm_V_last_V_1_vld_in;
wire    AXI_video_strm_V_last_V_1_vld_out;
wire    AXI_video_strm_V_last_V_1_ack_in;
wire    AXI_video_strm_V_last_V_1_ack_out;
reg   [0:0] AXI_video_strm_V_last_V_1_payload_A;
reg   [0:0] AXI_video_strm_V_last_V_1_payload_B;
reg    AXI_video_strm_V_last_V_1_sel_rd;
reg    AXI_video_strm_V_last_V_1_sel_wr;
wire    AXI_video_strm_V_last_V_1_sel;
wire    AXI_video_strm_V_last_V_1_load_A;
wire    AXI_video_strm_V_last_V_1_load_B;
reg   [1:0] AXI_video_strm_V_last_V_1_state;
wire    AXI_video_strm_V_last_V_1_state_cmp_full;
wire   [0:0] AXI_video_strm_V_id_V_1_data_out;
reg    AXI_video_strm_V_id_V_1_vld_in;
wire    AXI_video_strm_V_id_V_1_vld_out;
wire    AXI_video_strm_V_id_V_1_ack_in;
wire    AXI_video_strm_V_id_V_1_ack_out;
reg    AXI_video_strm_V_id_V_1_sel_rd;
wire    AXI_video_strm_V_id_V_1_sel;
reg   [1:0] AXI_video_strm_V_id_V_1_state;
wire   [0:0] AXI_video_strm_V_dest_V_1_data_out;
reg    AXI_video_strm_V_dest_V_1_vld_in;
wire    AXI_video_strm_V_dest_V_1_vld_out;
wire    AXI_video_strm_V_dest_V_1_ack_in;
wire    AXI_video_strm_V_dest_V_1_ack_out;
reg    AXI_video_strm_V_dest_V_1_sel_rd;
wire    AXI_video_strm_V_dest_V_1_sel;
reg   [1:0] AXI_video_strm_V_dest_V_1_state;
reg    strmPix_V_val_0_V_blk_n;
wire   [0:0] ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
reg   [0:0] exitcond2_reg_396;
reg    strmPix_V_val_1_V_blk_n;
reg    strmPix_V_val_2_V_blk_n;
reg    m_axis_video_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] ap_pipeline_reg_pp0_iter1_exitcond2_reg_396;
reg   [12:0] j_reg_178;
reg    ap_block_state1;
wire   [13:0] tmp_138_fu_210_p1;
reg   [13:0] tmp_138_reg_365;
wire   [0:0] ap_CS_fsm_state2;
wire    grp_reg_unsigned_short_s_fu_189_ap_done;
wire    grp_reg_unsigned_short_s_fu_195_ap_done;
reg    ap_block_state2_subcall_not_done;
wire   [12:0] tmp_139_fu_214_p1;
reg   [12:0] tmp_139_reg_370;
wire  signed [13:0] tmp_130_cast_fu_224_p1;
reg  signed [13:0] tmp_130_cast_reg_375;
wire   [0:0] sel_tmp2_fu_228_p2;
wire   [0:0] exitcond1_fu_238_p2;
wire   [0:0] ap_CS_fsm_state3;
reg    ap_block_state3;
wire   [11:0] i_1_fu_243_p2;
reg   [11:0] i_1_reg_391;
wire   [0:0] exitcond2_fu_253_p2;
reg    ap_block_state5_io;
wire    strmPix_V_val_0_V0_status;
reg    ap_block_state5;
reg    ap_block_state6_io;
wire   [12:0] j_1_fu_258_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] axi_last_V_fu_264_p2;
reg   [0:0] axi_last_V_reg_405;
wire   [23:0] tmp_data_V_fu_330_p5;
wire    grp_reg_unsigned_short_s_fu_189_ap_start;
wire    grp_reg_unsigned_short_s_fu_189_ap_idle;
wire    grp_reg_unsigned_short_s_fu_189_ap_ready;
wire   [15:0] grp_reg_unsigned_short_s_fu_189_ap_return;
wire    grp_reg_unsigned_short_s_fu_195_ap_start;
wire    grp_reg_unsigned_short_s_fu_195_ap_idle;
wire    grp_reg_unsigned_short_s_fu_195_ap_ready;
wire   [15:0] grp_reg_unsigned_short_s_fu_195_ap_return;
reg   [11:0] i_reg_167;
wire   [0:0] ap_CS_fsm_state7;
reg    ap_reg_grp_reg_unsigned_short_s_fu_189_ap_start;
reg    ap_block_state1_ignore_call8;
reg    ap_reg_grp_reg_unsigned_short_s_fu_195_ap_start;
reg    ap_block_state1_ignore_call9;
reg    strmPix_V_val_0_V0_update;
reg   [0:0] tmp_user_V_fu_106;
wire   [12:0] tmp_137_fu_206_p1;
wire   [12:0] tmp_123_fu_218_p2;
wire   [12:0] i_cast_fu_234_p1;
wire   [13:0] j_cast_fu_249_p1;
wire   [23:0] p_Result_s_fu_293_p3;
wire   [23:0] p_Result_2_fu_285_p3;
wire   [7:0] tmp_25_fu_315_p3;
wire   [7:0] tmp_24_fu_308_p3;
wire   [23:0] axi_0_2_fu_301_p3;
wire   [15:0] tmp_26_fu_322_p3;
reg   [4:0] ap_NS_fsm;
reg    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 AXI_video_strm_V_data_V_1_sel_rd = 1'b0;
#0 AXI_video_strm_V_data_V_1_sel_wr = 1'b0;
#0 AXI_video_strm_V_data_V_1_state = 2'd0;
#0 AXI_video_strm_V_keep_V_1_sel_rd = 1'b0;
#0 AXI_video_strm_V_keep_V_1_state = 2'd0;
#0 AXI_video_strm_V_strb_V_1_sel_rd = 1'b0;
#0 AXI_video_strm_V_strb_V_1_state = 2'd0;
#0 AXI_video_strm_V_user_V_1_sel_rd = 1'b0;
#0 AXI_video_strm_V_user_V_1_sel_wr = 1'b0;
#0 AXI_video_strm_V_user_V_1_state = 2'd0;
#0 AXI_video_strm_V_last_V_1_sel_rd = 1'b0;
#0 AXI_video_strm_V_last_V_1_sel_wr = 1'b0;
#0 AXI_video_strm_V_last_V_1_state = 2'd0;
#0 AXI_video_strm_V_id_V_1_sel_rd = 1'b0;
#0 AXI_video_strm_V_id_V_1_state = 2'd0;
#0 AXI_video_strm_V_dest_V_1_sel_rd = 1'b0;
#0 AXI_video_strm_V_dest_V_1_state = 2'd0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_reg_grp_reg_unsigned_short_s_fu_189_ap_start = 1'b0;
#0 ap_reg_grp_reg_unsigned_short_s_fu_195_ap_start = 1'b0;
end

design_1_v_tpg_0_0_reg_unsigned_short_s grp_reg_unsigned_short_s_fu_189(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_reg_unsigned_short_s_fu_189_ap_start),
    .ap_done(grp_reg_unsigned_short_s_fu_189_ap_done),
    .ap_idle(grp_reg_unsigned_short_s_fu_189_ap_idle),
    .ap_ready(grp_reg_unsigned_short_s_fu_189_ap_ready),
    .in_r(Height),
    .ap_return(grp_reg_unsigned_short_s_fu_189_ap_return)
);

design_1_v_tpg_0_0_reg_unsigned_short_s grp_reg_unsigned_short_s_fu_195(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_reg_unsigned_short_s_fu_195_ap_start),
    .ap_done(grp_reg_unsigned_short_s_fu_195_ap_done),
    .ap_idle(grp_reg_unsigned_short_s_fu_195_ap_idle),
    .ap_ready(grp_reg_unsigned_short_s_fu_195_ap_ready),
    .in_r(WidthOut),
    .ap_return(grp_reg_unsigned_short_s_fu_195_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        AXI_video_strm_V_data_V_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == AXI_video_strm_V_data_V_1_ack_out) & (1'b1 == AXI_video_strm_V_data_V_1_vld_out))) begin
            AXI_video_strm_V_data_V_1_sel_rd <= ~AXI_video_strm_V_data_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        AXI_video_strm_V_data_V_1_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == AXI_video_strm_V_data_V_1_vld_in) & (1'b1 == AXI_video_strm_V_data_V_1_ack_in))) begin
            AXI_video_strm_V_data_V_1_sel_wr <= ~AXI_video_strm_V_data_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        AXI_video_strm_V_data_V_1_state <= 2'd0;
    end else begin
        if ((((1'b0 == AXI_video_strm_V_data_V_1_vld_in) & (1'b1 == AXI_video_strm_V_data_V_1_ack_out) & (AXI_video_strm_V_data_V_1_state == 2'd3)) | ((1'b0 == AXI_video_strm_V_data_V_1_vld_in) & (AXI_video_strm_V_data_V_1_state == 2'd2)))) begin
            AXI_video_strm_V_data_V_1_state <= 2'd2;
        end else if ((((1'b1 == AXI_video_strm_V_data_V_1_vld_in) & (1'b0 == AXI_video_strm_V_data_V_1_ack_out) & (AXI_video_strm_V_data_V_1_state == 2'd3)) | ((1'b0 == AXI_video_strm_V_data_V_1_ack_out) & (AXI_video_strm_V_data_V_1_state == 2'd1)))) begin
            AXI_video_strm_V_data_V_1_state <= 2'd1;
        end else if ((((1'b1 == AXI_video_strm_V_data_V_1_vld_in) & (AXI_video_strm_V_data_V_1_state == 2'd2)) | ((1'b1 == AXI_video_strm_V_data_V_1_ack_out) & (AXI_video_strm_V_data_V_1_state == 2'd1)) | ((AXI_video_strm_V_data_V_1_state == 2'd3) & ~((1'b1 == AXI_video_strm_V_data_V_1_vld_in) & (1'b0 == AXI_video_strm_V_data_V_1_ack_out)) & ~((1'b0 == AXI_video_strm_V_data_V_1_vld_in) & (1'b1 == AXI_video_strm_V_data_V_1_ack_out))))) begin
            AXI_video_strm_V_data_V_1_state <= 2'd3;
        end else begin
            AXI_video_strm_V_data_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        AXI_video_strm_V_dest_V_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == AXI_video_strm_V_dest_V_1_ack_out) & (1'b1 == AXI_video_strm_V_dest_V_1_vld_out))) begin
            AXI_video_strm_V_dest_V_1_sel_rd <= ~AXI_video_strm_V_dest_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        AXI_video_strm_V_dest_V_1_state <= 2'd0;
    end else begin
        if ((((1'b0 == AXI_video_strm_V_dest_V_1_vld_in) & (1'b1 == AXI_video_strm_V_dest_V_1_ack_out) & (2'd3 == AXI_video_strm_V_dest_V_1_state)) | ((1'b0 == AXI_video_strm_V_dest_V_1_vld_in) & (2'd2 == AXI_video_strm_V_dest_V_1_state)))) begin
            AXI_video_strm_V_dest_V_1_state <= 2'd2;
        end else if ((((1'b1 == AXI_video_strm_V_dest_V_1_vld_in) & (1'b0 == AXI_video_strm_V_dest_V_1_ack_out) & (2'd3 == AXI_video_strm_V_dest_V_1_state)) | ((1'b0 == AXI_video_strm_V_dest_V_1_ack_out) & (2'd1 == AXI_video_strm_V_dest_V_1_state)))) begin
            AXI_video_strm_V_dest_V_1_state <= 2'd1;
        end else if ((((1'b1 == AXI_video_strm_V_dest_V_1_vld_in) & (2'd2 == AXI_video_strm_V_dest_V_1_state)) | ((1'b1 == AXI_video_strm_V_dest_V_1_ack_out) & (2'd1 == AXI_video_strm_V_dest_V_1_state)) | ((2'd3 == AXI_video_strm_V_dest_V_1_state) & ~((1'b1 == AXI_video_strm_V_dest_V_1_vld_in) & (1'b0 == AXI_video_strm_V_dest_V_1_ack_out)) & ~((1'b0 == AXI_video_strm_V_dest_V_1_vld_in) & (1'b1 == AXI_video_strm_V_dest_V_1_ack_out))))) begin
            AXI_video_strm_V_dest_V_1_state <= 2'd3;
        end else begin
            AXI_video_strm_V_dest_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        AXI_video_strm_V_id_V_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == AXI_video_strm_V_id_V_1_ack_out) & (1'b1 == AXI_video_strm_V_id_V_1_vld_out))) begin
            AXI_video_strm_V_id_V_1_sel_rd <= ~AXI_video_strm_V_id_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        AXI_video_strm_V_id_V_1_state <= 2'd0;
    end else begin
        if ((((1'b0 == AXI_video_strm_V_id_V_1_vld_in) & (1'b1 == AXI_video_strm_V_id_V_1_ack_out) & (2'd3 == AXI_video_strm_V_id_V_1_state)) | ((1'b0 == AXI_video_strm_V_id_V_1_vld_in) & (2'd2 == AXI_video_strm_V_id_V_1_state)))) begin
            AXI_video_strm_V_id_V_1_state <= 2'd2;
        end else if ((((1'b1 == AXI_video_strm_V_id_V_1_vld_in) & (1'b0 == AXI_video_strm_V_id_V_1_ack_out) & (2'd3 == AXI_video_strm_V_id_V_1_state)) | ((1'b0 == AXI_video_strm_V_id_V_1_ack_out) & (2'd1 == AXI_video_strm_V_id_V_1_state)))) begin
            AXI_video_strm_V_id_V_1_state <= 2'd1;
        end else if ((((1'b1 == AXI_video_strm_V_id_V_1_vld_in) & (2'd2 == AXI_video_strm_V_id_V_1_state)) | ((1'b1 == AXI_video_strm_V_id_V_1_ack_out) & (2'd1 == AXI_video_strm_V_id_V_1_state)) | ((2'd3 == AXI_video_strm_V_id_V_1_state) & ~((1'b1 == AXI_video_strm_V_id_V_1_vld_in) & (1'b0 == AXI_video_strm_V_id_V_1_ack_out)) & ~((1'b0 == AXI_video_strm_V_id_V_1_vld_in) & (1'b1 == AXI_video_strm_V_id_V_1_ack_out))))) begin
            AXI_video_strm_V_id_V_1_state <= 2'd3;
        end else begin
            AXI_video_strm_V_id_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        AXI_video_strm_V_keep_V_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == AXI_video_strm_V_keep_V_1_ack_out) & (1'b1 == AXI_video_strm_V_keep_V_1_vld_out))) begin
            AXI_video_strm_V_keep_V_1_sel_rd <= ~AXI_video_strm_V_keep_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        AXI_video_strm_V_keep_V_1_state <= 2'd0;
    end else begin
        if ((((1'b0 == AXI_video_strm_V_keep_V_1_vld_in) & (1'b1 == AXI_video_strm_V_keep_V_1_ack_out) & (2'd3 == AXI_video_strm_V_keep_V_1_state)) | ((1'b0 == AXI_video_strm_V_keep_V_1_vld_in) & (2'd2 == AXI_video_strm_V_keep_V_1_state)))) begin
            AXI_video_strm_V_keep_V_1_state <= 2'd2;
        end else if ((((1'b1 == AXI_video_strm_V_keep_V_1_vld_in) & (1'b0 == AXI_video_strm_V_keep_V_1_ack_out) & (2'd3 == AXI_video_strm_V_keep_V_1_state)) | ((1'b0 == AXI_video_strm_V_keep_V_1_ack_out) & (2'd1 == AXI_video_strm_V_keep_V_1_state)))) begin
            AXI_video_strm_V_keep_V_1_state <= 2'd1;
        end else if ((((1'b1 == AXI_video_strm_V_keep_V_1_vld_in) & (2'd2 == AXI_video_strm_V_keep_V_1_state)) | ((1'b1 == AXI_video_strm_V_keep_V_1_ack_out) & (2'd1 == AXI_video_strm_V_keep_V_1_state)) | ((2'd3 == AXI_video_strm_V_keep_V_1_state) & ~((1'b1 == AXI_video_strm_V_keep_V_1_vld_in) & (1'b0 == AXI_video_strm_V_keep_V_1_ack_out)) & ~((1'b0 == AXI_video_strm_V_keep_V_1_vld_in) & (1'b1 == AXI_video_strm_V_keep_V_1_ack_out))))) begin
            AXI_video_strm_V_keep_V_1_state <= 2'd3;
        end else begin
            AXI_video_strm_V_keep_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        AXI_video_strm_V_last_V_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == AXI_video_strm_V_last_V_1_ack_out) & (1'b1 == AXI_video_strm_V_last_V_1_vld_out))) begin
            AXI_video_strm_V_last_V_1_sel_rd <= ~AXI_video_strm_V_last_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        AXI_video_strm_V_last_V_1_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == AXI_video_strm_V_last_V_1_vld_in) & (1'b1 == AXI_video_strm_V_last_V_1_ack_in))) begin
            AXI_video_strm_V_last_V_1_sel_wr <= ~AXI_video_strm_V_last_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        AXI_video_strm_V_last_V_1_state <= 2'd0;
    end else begin
        if ((((1'b0 == AXI_video_strm_V_last_V_1_vld_in) & (1'b1 == AXI_video_strm_V_last_V_1_ack_out) & (2'd3 == AXI_video_strm_V_last_V_1_state)) | ((1'b0 == AXI_video_strm_V_last_V_1_vld_in) & (2'd2 == AXI_video_strm_V_last_V_1_state)))) begin
            AXI_video_strm_V_last_V_1_state <= 2'd2;
        end else if ((((1'b1 == AXI_video_strm_V_last_V_1_vld_in) & (1'b0 == AXI_video_strm_V_last_V_1_ack_out) & (2'd3 == AXI_video_strm_V_last_V_1_state)) | ((1'b0 == AXI_video_strm_V_last_V_1_ack_out) & (2'd1 == AXI_video_strm_V_last_V_1_state)))) begin
            AXI_video_strm_V_last_V_1_state <= 2'd1;
        end else if ((((1'b1 == AXI_video_strm_V_last_V_1_vld_in) & (2'd2 == AXI_video_strm_V_last_V_1_state)) | ((1'b1 == AXI_video_strm_V_last_V_1_ack_out) & (2'd1 == AXI_video_strm_V_last_V_1_state)) | ((2'd3 == AXI_video_strm_V_last_V_1_state) & ~((1'b1 == AXI_video_strm_V_last_V_1_vld_in) & (1'b0 == AXI_video_strm_V_last_V_1_ack_out)) & ~((1'b0 == AXI_video_strm_V_last_V_1_vld_in) & (1'b1 == AXI_video_strm_V_last_V_1_ack_out))))) begin
            AXI_video_strm_V_last_V_1_state <= 2'd3;
        end else begin
            AXI_video_strm_V_last_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        AXI_video_strm_V_strb_V_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == AXI_video_strm_V_strb_V_1_ack_out) & (1'b1 == AXI_video_strm_V_strb_V_1_vld_out))) begin
            AXI_video_strm_V_strb_V_1_sel_rd <= ~AXI_video_strm_V_strb_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        AXI_video_strm_V_strb_V_1_state <= 2'd0;
    end else begin
        if ((((1'b0 == AXI_video_strm_V_strb_V_1_vld_in) & (1'b1 == AXI_video_strm_V_strb_V_1_ack_out) & (2'd3 == AXI_video_strm_V_strb_V_1_state)) | ((1'b0 == AXI_video_strm_V_strb_V_1_vld_in) & (2'd2 == AXI_video_strm_V_strb_V_1_state)))) begin
            AXI_video_strm_V_strb_V_1_state <= 2'd2;
        end else if ((((1'b1 == AXI_video_strm_V_strb_V_1_vld_in) & (1'b0 == AXI_video_strm_V_strb_V_1_ack_out) & (2'd3 == AXI_video_strm_V_strb_V_1_state)) | ((1'b0 == AXI_video_strm_V_strb_V_1_ack_out) & (2'd1 == AXI_video_strm_V_strb_V_1_state)))) begin
            AXI_video_strm_V_strb_V_1_state <= 2'd1;
        end else if ((((1'b1 == AXI_video_strm_V_strb_V_1_vld_in) & (2'd2 == AXI_video_strm_V_strb_V_1_state)) | ((1'b1 == AXI_video_strm_V_strb_V_1_ack_out) & (2'd1 == AXI_video_strm_V_strb_V_1_state)) | ((2'd3 == AXI_video_strm_V_strb_V_1_state) & ~((1'b1 == AXI_video_strm_V_strb_V_1_vld_in) & (1'b0 == AXI_video_strm_V_strb_V_1_ack_out)) & ~((1'b0 == AXI_video_strm_V_strb_V_1_vld_in) & (1'b1 == AXI_video_strm_V_strb_V_1_ack_out))))) begin
            AXI_video_strm_V_strb_V_1_state <= 2'd3;
        end else begin
            AXI_video_strm_V_strb_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        AXI_video_strm_V_user_V_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == AXI_video_strm_V_user_V_1_ack_out) & (1'b1 == AXI_video_strm_V_user_V_1_vld_out))) begin
            AXI_video_strm_V_user_V_1_sel_rd <= ~AXI_video_strm_V_user_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        AXI_video_strm_V_user_V_1_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == AXI_video_strm_V_user_V_1_vld_in) & (1'b1 == AXI_video_strm_V_user_V_1_ack_in))) begin
            AXI_video_strm_V_user_V_1_sel_wr <= ~AXI_video_strm_V_user_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        AXI_video_strm_V_user_V_1_state <= 2'd0;
    end else begin
        if ((((1'b0 == AXI_video_strm_V_user_V_1_vld_in) & (1'b1 == AXI_video_strm_V_user_V_1_ack_out) & (2'd3 == AXI_video_strm_V_user_V_1_state)) | ((1'b0 == AXI_video_strm_V_user_V_1_vld_in) & (2'd2 == AXI_video_strm_V_user_V_1_state)))) begin
            AXI_video_strm_V_user_V_1_state <= 2'd2;
        end else if ((((1'b1 == AXI_video_strm_V_user_V_1_vld_in) & (1'b0 == AXI_video_strm_V_user_V_1_ack_out) & (2'd3 == AXI_video_strm_V_user_V_1_state)) | ((1'b0 == AXI_video_strm_V_user_V_1_ack_out) & (2'd1 == AXI_video_strm_V_user_V_1_state)))) begin
            AXI_video_strm_V_user_V_1_state <= 2'd1;
        end else if ((((1'b1 == AXI_video_strm_V_user_V_1_vld_in) & (2'd2 == AXI_video_strm_V_user_V_1_state)) | ((1'b1 == AXI_video_strm_V_user_V_1_ack_out) & (2'd1 == AXI_video_strm_V_user_V_1_state)) | ((2'd3 == AXI_video_strm_V_user_V_1_state) & ~((1'b1 == AXI_video_strm_V_user_V_1_vld_in) & (1'b0 == AXI_video_strm_V_user_V_1_ack_out)) & ~((1'b0 == AXI_video_strm_V_user_V_1_vld_in) & (1'b1 == AXI_video_strm_V_user_V_1_ack_out))))) begin
            AXI_video_strm_V_user_V_1_state <= 2'd3;
        end else begin
            AXI_video_strm_V_user_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= 5'd1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_continue)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'd1 == ap_CS_fsm_state3) & ~(1'b1 == ap_block_state3) & ~(1'd0 == exitcond1_fu_238_p2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'd1 == ap_CS_fsm_pp0_stage0) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_block_state6_io))) & ~(1'd0 == exitcond2_fu_253_p2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'd1 == ap_CS_fsm_state3) & ~(1'b1 == ap_block_state3) & (1'd0 == exitcond1_fu_238_p2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'd1 == ap_CS_fsm_pp0_stage0) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_block_state6_io))) & (1'd0 == exitcond2_fu_253_p2))) begin
            ap_enable_reg_pp0_iter1 <= 1'b1;
        end else if ((((1'd1 == ap_CS_fsm_state3) & ~(1'b1 == ap_block_state3) & (1'd0 == exitcond1_fu_238_p2)) | ((1'd1 == ap_CS_fsm_pp0_stage0) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_block_state6_io))) & ~(1'd0 == exitcond2_fu_253_p2)))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_enable_reg_pp0_iter1) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_block_state6_io)))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((1'd1 == ap_CS_fsm_state3) & ~(1'b1 == ap_block_state3) & (1'd0 == exitcond1_fu_238_p2))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_reg_unsigned_short_s_fu_189_ap_start <= 1'b0;
    end else begin
        if (((ap_CS_fsm_state1 == 1'd1) & ~(1'b1 == ap_block_state1_ignore_call8))) begin
            ap_reg_grp_reg_unsigned_short_s_fu_189_ap_start <= 1'b1;
        end else if ((1'b1 == grp_reg_unsigned_short_s_fu_189_ap_ready)) begin
            ap_reg_grp_reg_unsigned_short_s_fu_189_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_reg_unsigned_short_s_fu_195_ap_start <= 1'b0;
    end else begin
        if (((ap_CS_fsm_state1 == 1'd1) & ~(1'b1 == ap_block_state1_ignore_call9))) begin
            ap_reg_grp_reg_unsigned_short_s_fu_195_ap_start <= 1'b1;
        end else if ((1'b1 == grp_reg_unsigned_short_s_fu_195_ap_ready)) begin
            ap_reg_grp_reg_unsigned_short_s_fu_195_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'd1 == ap_CS_fsm_state7)) begin
        i_reg_167 <= i_1_reg_391;
    end else if (((1'd1 == ap_CS_fsm_state2) & ~(1'b1 == ap_block_state2_subcall_not_done))) begin
        i_reg_167 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == ap_CS_fsm_state3) & ~(1'b1 == ap_block_state3) & (1'd0 == exitcond1_fu_238_p2))) begin
        j_reg_178 <= 13'd0;
    end else if (((1'd1 == ap_CS_fsm_pp0_stage0) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_block_state6_io))) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'd0 == exitcond2_fu_253_p2))) begin
        j_reg_178 <= j_1_fu_258_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd0 == exitcond2_reg_396) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_block_state6_io))))) begin
        tmp_user_V_fu_106 <= 1'd0;
    end else if (((ap_CS_fsm_state1 == 1'd1) & ~(1'b1 == ap_block_state1))) begin
        tmp_user_V_fu_106 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == AXI_video_strm_V_data_V_1_load_A)) begin
        AXI_video_strm_V_data_V_1_payload_A <= tmp_data_V_fu_330_p5;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == AXI_video_strm_V_data_V_1_load_B)) begin
        AXI_video_strm_V_data_V_1_payload_B <= tmp_data_V_fu_330_p5;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == AXI_video_strm_V_last_V_1_load_A)) begin
        AXI_video_strm_V_last_V_1_payload_A <= axi_last_V_reg_405;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == AXI_video_strm_V_last_V_1_load_B)) begin
        AXI_video_strm_V_last_V_1_payload_B <= axi_last_V_reg_405;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == AXI_video_strm_V_user_V_1_load_A)) begin
        AXI_video_strm_V_user_V_1_payload_A <= tmp_user_V_fu_106;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == AXI_video_strm_V_user_V_1_load_B)) begin
        AXI_video_strm_V_user_V_1_payload_B <= tmp_user_V_fu_106;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == ap_CS_fsm_pp0_stage0) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_block_state6_io))))) begin
        ap_pipeline_reg_pp0_iter1_exitcond2_reg_396 <= exitcond2_reg_396;
        exitcond2_reg_396 <= exitcond2_fu_253_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == ap_CS_fsm_pp0_stage0) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_block_state6_io))) & (1'd0 == exitcond2_fu_253_p2))) begin
        axi_last_V_reg_405 <= axi_last_V_fu_264_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == ap_CS_fsm_state3) & ~(1'b1 == ap_block_state3))) begin
        i_1_reg_391 <= i_1_fu_243_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == ap_CS_fsm_state2) & ~(1'b1 == ap_block_state2_subcall_not_done))) begin
        tmp_130_cast_reg_375 <= tmp_130_cast_fu_224_p1;
        tmp_138_reg_365 <= tmp_138_fu_210_p1;
        tmp_139_reg_370 <= tmp_139_fu_214_p1;
    end
end

always @ (*) begin
    if ((1'b1 == AXI_video_strm_V_data_V_1_sel)) begin
        AXI_video_strm_V_data_V_1_data_out = AXI_video_strm_V_data_V_1_payload_B;
    end else begin
        AXI_video_strm_V_data_V_1_data_out = AXI_video_strm_V_data_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'd1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd0 == exitcond2_reg_396) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_block_state6_io))))) begin
        AXI_video_strm_V_data_V_1_vld_in = 1'b1;
    end else begin
        AXI_video_strm_V_data_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd0 == exitcond2_reg_396) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_block_state6_io))))) begin
        AXI_video_strm_V_dest_V_1_vld_in = 1'b1;
    end else begin
        AXI_video_strm_V_dest_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd0 == exitcond2_reg_396) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_block_state6_io))))) begin
        AXI_video_strm_V_id_V_1_vld_in = 1'b1;
    end else begin
        AXI_video_strm_V_id_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd0 == exitcond2_reg_396) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_block_state6_io))))) begin
        AXI_video_strm_V_keep_V_1_vld_in = 1'b1;
    end else begin
        AXI_video_strm_V_keep_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == AXI_video_strm_V_last_V_1_sel)) begin
        AXI_video_strm_V_last_V_1_data_out = AXI_video_strm_V_last_V_1_payload_B;
    end else begin
        AXI_video_strm_V_last_V_1_data_out = AXI_video_strm_V_last_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'd1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd0 == exitcond2_reg_396) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_block_state6_io))))) begin
        AXI_video_strm_V_last_V_1_vld_in = 1'b1;
    end else begin
        AXI_video_strm_V_last_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd0 == exitcond2_reg_396) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_block_state6_io))))) begin
        AXI_video_strm_V_strb_V_1_vld_in = 1'b1;
    end else begin
        AXI_video_strm_V_strb_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == AXI_video_strm_V_user_V_1_sel)) begin
        AXI_video_strm_V_user_V_1_data_out = AXI_video_strm_V_user_V_1_payload_B;
    end else begin
        AXI_video_strm_V_user_V_1_data_out = AXI_video_strm_V_user_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'd1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd0 == exitcond2_reg_396) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_block_state6_io))))) begin
        AXI_video_strm_V_user_V_1_vld_in = 1'b1;
    end else begin
        AXI_video_strm_V_user_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_done_reg) | ((1'd1 == ap_CS_fsm_state3) & ~(1'b1 == ap_block_state3) & ~(1'd0 == exitcond1_fu_238_p2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (ap_CS_fsm_state1 == 1'd1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == ap_CS_fsm_state3) & ~(1'b1 == ap_block_state3) & ~(1'd0 == exitcond1_fu_238_p2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((1'd1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd0 == exitcond2_reg_396)) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'd0 == ap_pipeline_reg_pp0_iter1_exitcond2_reg_396)))) begin
        m_axis_video_TDATA_blk_n = AXI_video_strm_V_data_V_1_state[1'd1];
    end else begin
        m_axis_video_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'd1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd0 == exitcond2_reg_396) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_block_state6_io))))) begin
        strmPix_V_val_0_V0_update = 1'b1;
    end else begin
        strmPix_V_val_0_V0_update = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd0 == exitcond2_reg_396))) begin
        strmPix_V_val_0_V_blk_n = strmPix_V_val_0_V_empty_n;
    end else begin
        strmPix_V_val_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'd1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd0 == exitcond2_reg_396))) begin
        strmPix_V_val_1_V_blk_n = strmPix_V_val_1_V_empty_n;
    end else begin
        strmPix_V_val_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'd1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd0 == exitcond2_reg_396))) begin
        strmPix_V_val_2_V_blk_n = strmPix_V_val_2_V_empty_n;
    end else begin
        strmPix_V_val_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        5'd1 : begin
            if (~(1'b1 == ap_block_state1)) begin
                ap_NS_fsm = 5'd2;
            end else begin
                ap_NS_fsm = 5'd1;
            end
        end
        5'd2 : begin
            if (~(1'b1 == ap_block_state2_subcall_not_done)) begin
                ap_NS_fsm = 5'd4;
            end else begin
                ap_NS_fsm = 5'd2;
            end
        end
        5'd4 : begin
            if ((~(1'b1 == ap_block_state3) & ~(1'd0 == exitcond1_fu_238_p2))) begin
                ap_NS_fsm = 5'd1;
            end else if ((~(1'b1 == ap_block_state3) & (1'd0 == exitcond1_fu_238_p2))) begin
                ap_NS_fsm = 5'd8;
            end else begin
                ap_NS_fsm = 5'd4;
            end
        end
        5'd8 : begin
            if ((~((1'b1 == ap_enable_reg_pp0_iter2) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_block_state6_io))) & ~(1'b1 == ap_enable_reg_pp0_iter1)) & ~(~(((1'b1 == ap_enable_reg_pp0_iter1) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_block_state6_io))) & (1'b1 == ap_enable_reg_pp0_iter0) & ~(1'd0 == exitcond2_fu_253_p2) & ~(1'b1 == ap_enable_reg_pp0_iter1)))) begin
                ap_NS_fsm = 5'd8;
            end else if ((((1'b1 == ap_enable_reg_pp0_iter2) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_block_state6_io))) & ~(1'b1 == ap_enable_reg_pp0_iter1)) | (~(((1'b1 == ap_enable_reg_pp0_iter1) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_block_state6_io))) & (1'b1 == ap_enable_reg_pp0_iter0) & ~(1'd0 == exitcond2_fu_253_p2) & ~(1'b1 == ap_enable_reg_pp0_iter1)))) begin
                ap_NS_fsm = 5'd16;
            end else begin
                ap_NS_fsm = 5'd8;
            end
        end
        5'd16 : begin
            ap_NS_fsm = 5'd4;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign AXI_video_strm_V_data_V_1_ack_in = AXI_video_strm_V_data_V_1_state[1'd1];

assign AXI_video_strm_V_data_V_1_ack_out = m_axis_video_TREADY;

assign AXI_video_strm_V_data_V_1_load_A = (AXI_video_strm_V_data_V_1_state_cmp_full & ~AXI_video_strm_V_data_V_1_sel_wr);

assign AXI_video_strm_V_data_V_1_load_B = (AXI_video_strm_V_data_V_1_sel_wr & AXI_video_strm_V_data_V_1_state_cmp_full);

assign AXI_video_strm_V_data_V_1_sel = AXI_video_strm_V_data_V_1_sel_rd;

assign AXI_video_strm_V_data_V_1_state_cmp_full = ((AXI_video_strm_V_data_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign AXI_video_strm_V_data_V_1_vld_out = AXI_video_strm_V_data_V_1_state[1'd0];

assign AXI_video_strm_V_dest_V_1_ack_in = AXI_video_strm_V_dest_V_1_state[1'd1];

assign AXI_video_strm_V_dest_V_1_ack_out = m_axis_video_TREADY;

assign AXI_video_strm_V_dest_V_1_data_out = 1'd0;

assign AXI_video_strm_V_dest_V_1_sel = AXI_video_strm_V_dest_V_1_sel_rd;

assign AXI_video_strm_V_dest_V_1_vld_out = AXI_video_strm_V_dest_V_1_state[1'd0];

assign AXI_video_strm_V_id_V_1_ack_in = AXI_video_strm_V_id_V_1_state[1'd1];

assign AXI_video_strm_V_id_V_1_ack_out = m_axis_video_TREADY;

assign AXI_video_strm_V_id_V_1_data_out = 1'd0;

assign AXI_video_strm_V_id_V_1_sel = AXI_video_strm_V_id_V_1_sel_rd;

assign AXI_video_strm_V_id_V_1_vld_out = AXI_video_strm_V_id_V_1_state[1'd0];

assign AXI_video_strm_V_keep_V_1_ack_in = AXI_video_strm_V_keep_V_1_state[1'd1];

assign AXI_video_strm_V_keep_V_1_ack_out = m_axis_video_TREADY;

assign AXI_video_strm_V_keep_V_1_data_out = 3'd7;

assign AXI_video_strm_V_keep_V_1_sel = AXI_video_strm_V_keep_V_1_sel_rd;

assign AXI_video_strm_V_keep_V_1_vld_out = AXI_video_strm_V_keep_V_1_state[1'd0];

assign AXI_video_strm_V_last_V_1_ack_in = AXI_video_strm_V_last_V_1_state[1'd1];

assign AXI_video_strm_V_last_V_1_ack_out = m_axis_video_TREADY;

assign AXI_video_strm_V_last_V_1_load_A = (AXI_video_strm_V_last_V_1_state_cmp_full & ~AXI_video_strm_V_last_V_1_sel_wr);

assign AXI_video_strm_V_last_V_1_load_B = (AXI_video_strm_V_last_V_1_sel_wr & AXI_video_strm_V_last_V_1_state_cmp_full);

assign AXI_video_strm_V_last_V_1_sel = AXI_video_strm_V_last_V_1_sel_rd;

assign AXI_video_strm_V_last_V_1_state_cmp_full = ((AXI_video_strm_V_last_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign AXI_video_strm_V_last_V_1_vld_out = AXI_video_strm_V_last_V_1_state[1'd0];

assign AXI_video_strm_V_strb_V_1_ack_in = AXI_video_strm_V_strb_V_1_state[1'd1];

assign AXI_video_strm_V_strb_V_1_ack_out = m_axis_video_TREADY;

assign AXI_video_strm_V_strb_V_1_data_out = 3'd0;

assign AXI_video_strm_V_strb_V_1_sel = AXI_video_strm_V_strb_V_1_sel_rd;

assign AXI_video_strm_V_strb_V_1_vld_out = AXI_video_strm_V_strb_V_1_state[1'd0];

assign AXI_video_strm_V_user_V_1_ack_in = AXI_video_strm_V_user_V_1_state[1'd1];

assign AXI_video_strm_V_user_V_1_ack_out = m_axis_video_TREADY;

assign AXI_video_strm_V_user_V_1_load_A = (AXI_video_strm_V_user_V_1_state_cmp_full & ~AXI_video_strm_V_user_V_1_sel_wr);

assign AXI_video_strm_V_user_V_1_load_B = (AXI_video_strm_V_user_V_1_sel_wr & AXI_video_strm_V_user_V_1_state_cmp_full);

assign AXI_video_strm_V_user_V_1_sel = AXI_video_strm_V_user_V_1_sel_rd;

assign AXI_video_strm_V_user_V_1_state_cmp_full = ((AXI_video_strm_V_user_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign AXI_video_strm_V_user_V_1_vld_out = AXI_video_strm_V_user_V_1_state[1'd0];

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((1'b0 == ap_start) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call8 = ((1'b0 == ap_start) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call9 = ((1'b0 == ap_start) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2_subcall_not_done = ((1'b0 == grp_reg_unsigned_short_s_fu_189_ap_done) | (1'b0 == grp_reg_unsigned_short_s_fu_195_ap_done));
end

always @ (*) begin
    ap_block_state3 = ((1'b0 == AXI_video_strm_V_data_V_1_ack_in) | (1'b0 == AXI_video_strm_V_keep_V_1_ack_in) | (1'b0 == AXI_video_strm_V_strb_V_1_ack_in) | (1'b0 == AXI_video_strm_V_user_V_1_ack_in) | (1'b0 == AXI_video_strm_V_last_V_1_ack_in) | (1'b0 == AXI_video_strm_V_id_V_1_ack_in) | (1'b0 == AXI_video_strm_V_dest_V_1_ack_in));
end

always @ (*) begin
    ap_block_state5 = ((1'd0 == exitcond2_reg_396) & (1'b0 == strmPix_V_val_0_V0_status));
end

always @ (*) begin
    ap_block_state5_io = ((1'd0 == exitcond2_reg_396) & (1'b0 == AXI_video_strm_V_data_V_1_ack_in));
end

always @ (*) begin
    ap_block_state6_io = ((1'd0 == ap_pipeline_reg_pp0_iter1_exitcond2_reg_396) & (1'b0 == AXI_video_strm_V_data_V_1_ack_in));
end

always @ (*) begin
    ap_enable_pp0 = ((ap_enable_reg_pp0_iter0 == 1'b1) | (ap_enable_reg_pp0_iter1 == 1'b1) | (ap_enable_reg_pp0_iter2 == 1'b1));
end

assign axi_0_2_fu_301_p3 = ((sel_tmp2_fu_228_p2[0:0] === 1'b1) ? p_Result_s_fu_293_p3 : p_Result_2_fu_285_p3);

assign axi_last_V_fu_264_p2 = ((j_cast_fu_249_p1 == tmp_130_cast_reg_375) ? 1'b1 : 1'b0);

assign exitcond1_fu_238_p2 = ((i_cast_fu_234_p1 == tmp_139_reg_370) ? 1'b1 : 1'b0);

assign exitcond2_fu_253_p2 = ((j_cast_fu_249_p1 == tmp_138_reg_365) ? 1'b1 : 1'b0);

assign grp_reg_unsigned_short_s_fu_189_ap_start = ap_reg_grp_reg_unsigned_short_s_fu_189_ap_start;

assign grp_reg_unsigned_short_s_fu_195_ap_start = ap_reg_grp_reg_unsigned_short_s_fu_195_ap_start;

assign i_1_fu_243_p2 = (i_reg_167 + 12'd1);

assign i_cast_fu_234_p1 = i_reg_167;

assign j_1_fu_258_p2 = (j_reg_178 + 13'd1);

assign j_cast_fu_249_p1 = j_reg_178;

assign m_axis_video_TDATA = AXI_video_strm_V_data_V_1_data_out;

assign m_axis_video_TDEST = AXI_video_strm_V_dest_V_1_data_out;

assign m_axis_video_TID = AXI_video_strm_V_id_V_1_data_out;

assign m_axis_video_TKEEP = AXI_video_strm_V_keep_V_1_data_out;

assign m_axis_video_TLAST = AXI_video_strm_V_last_V_1_data_out;

assign m_axis_video_TSTRB = AXI_video_strm_V_strb_V_1_data_out;

assign m_axis_video_TUSER = AXI_video_strm_V_user_V_1_data_out;

assign m_axis_video_TVALID = AXI_video_strm_V_dest_V_1_state[1'd0];

assign p_Result_2_fu_285_p3 = {{16'd65535}, {strmPix_V_val_0_V_dout}};

assign p_Result_s_fu_293_p3 = {{16'd65535}, {strmPix_V_val_1_V_dout}};

assign sel_tmp2_fu_228_p2 = ((colorFormat == 8'd0) ? 1'b1 : 1'b0);

assign strmPix_V_val_0_V0_status = (strmPix_V_val_0_V_empty_n & strmPix_V_val_1_V_empty_n & strmPix_V_val_2_V_empty_n);

assign strmPix_V_val_0_V_read = strmPix_V_val_0_V0_update;

assign strmPix_V_val_1_V_read = strmPix_V_val_0_V0_update;

assign strmPix_V_val_2_V_read = strmPix_V_val_0_V0_update;

assign tmp_123_fu_218_p2 = ($signed(13'd8191) + $signed(tmp_137_fu_206_p1));

assign tmp_130_cast_fu_224_p1 = $signed(tmp_123_fu_218_p2);

assign tmp_137_fu_206_p1 = grp_reg_unsigned_short_s_fu_195_ap_return[12:0];

assign tmp_138_fu_210_p1 = grp_reg_unsigned_short_s_fu_195_ap_return[13:0];

assign tmp_139_fu_214_p1 = grp_reg_unsigned_short_s_fu_189_ap_return[12:0];

assign tmp_24_fu_308_p3 = ((sel_tmp2_fu_228_p2[0:0] === 1'b1) ? strmPix_V_val_2_V_dout : strmPix_V_val_1_V_dout);

assign tmp_25_fu_315_p3 = ((sel_tmp2_fu_228_p2[0:0] === 1'b1) ? strmPix_V_val_0_V_dout : strmPix_V_val_2_V_dout);

assign tmp_26_fu_322_p3 = {{tmp_25_fu_315_p3}, {tmp_24_fu_308_p3}};

assign tmp_data_V_fu_330_p5 = {{tmp_26_fu_322_p3}, {axi_0_2_fu_301_p3[7:0]}};

endmodule //design_1_v_tpg_0_0_MultiPixStream2AXIvi
