#!/bin/bash -f
# Vivado (TM) v2016.3_sdx (64-bit)
#
# Filename    : design_1.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Sat Sep 30 13:09:41 +0100 2017
# IP Build 1720686 on Mon Nov 28 12:39:17 MST 2016 
#
# usage: design_1.sh [-help]
# usage: design_1.sh [-lib_map_path]
# usage: design_1.sh [-noclean_files]
# usage: design_1.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'design_1.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
# ********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib xpm blk_mem_gen_v8_3_4 axi_bram_ctrl_v4_0_9 lib_cdc_v1_0_2 proc_sys_reset_v5_0_10 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_10 fifo_generator_v13_1_2 axi_data_fifo_v2_1_9 axi_crossbar_v2_1_11 axi_perf_mon_v5_0_12 lib_pkg_v1_0_2 lib_fifo_v1_0_6 lib_bmg_v1_0_6 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_12 axi_vdma_v6_2_9 v_tpg_v7_0_4 axi_protocol_converter_v2_1_10 axi_clock_converter_v2_1_9 axi_dwidth_converter_v2_1_10)

# Simulation root library directory
sim_lib_dir="vcs"

# Script info
echo -e "design_1.sh - Script generated by export_simulation (Vivado v2016.3_sdx (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/fb8f/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/a07a/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/8ef2/hdl/verilog" \
    "C:/Xilinx/SDx/2016.3/Vivado/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/SDx/2016.3/Vivado/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/SDx/2016.3/Vivado/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/fb8f/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/a07a/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/8ef2/hdl/verilog" \
    "$ref_dir/../../../bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0_sim_netlist.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_3_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/fb8f/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/a07a/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/8ef2/hdl/verilog" \
    "$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/59b0/simulation/blk_mem_gen_v8_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_bram_ctrl_v4_0_9 $vhdlan_opts \
    "$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/d95a/hdl/axi_bram_ctrl_v4_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_bram_ctrl_0_0/sim/design_1_axi_bram_ctrl_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/52cb/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_10 $vhdlan_opts \
    "$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/04b4/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_rst_ps8_0_100M_0/sim/design_1_rst_ps8_0_100M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/fb8f/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/a07a/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/8ef2/hdl/verilog" \
    "$ref_dir/../../../bd/design_1/ip/design_1_blk_mem_gen_0_0/sim/design_1_blk_mem_gen_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/fb8f/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/a07a/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/8ef2/hdl/verilog" \
    "$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/7ee0/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/fb8f/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/a07a/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/8ef2/hdl/verilog" \
    "$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/fb8f/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/a07a/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/8ef2/hdl/verilog" \
    "$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/7efe/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_1_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/fb8f/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/a07a/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/8ef2/hdl/verilog" \
    "$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/a807/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_1_2 $vhdlan_opts \
    "$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/a807/hdl/fifo_generator_v13_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_1_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/fb8f/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/a07a/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/8ef2/hdl/verilog" \
    "$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/a807/hdl/fifo_generator_v13_1_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/fb8f/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/a07a/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/8ef2/hdl/verilog" \
    "$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/10b8/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_11 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/fb8f/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/a07a/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/8ef2/hdl/verilog" \
    "$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/d552/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/fb8f/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/a07a/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/8ef2/hdl/verilog" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xbar_0/sim/design_1_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_perf_mon_v5_0_12 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/fb8f/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/a07a/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/8ef2/hdl/verilog" \
    "$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/19c4/hdl/axi_perf_mon_v5_0_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/fb8f/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/a07a/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/8ef2/hdl/verilog" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_perf_mon_0_0/sim/design_1_axi_perf_mon_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ipshared/2e37/xlconcat.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_0_0/sim/design_1_xlconcat_0_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_bram_ctrl_0_1/sim/design_1_axi_bram_ctrl_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/fb8f/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/a07a/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/8ef2/hdl/verilog" \
    "$ref_dir/../../../bd/design_1/ip/design_1_blk_mem_gen_0_1/sim/design_1_blk_mem_gen_0_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_perf_mon_0_1/sim/design_1_axi_perf_mon_0_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xbar_1/sim/design_1_xbar_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/832a/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_fifo_v1_0_6 $vhdlan_opts \
    "$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/61a7/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_bmg_v1_0_6 $vhdlan_opts \
    "$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/7d44/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/6039/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_12 $vhdlan_opts \
    "$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/1cd0/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_vdma_v6_2_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/fb8f/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/a07a/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/8ef2/hdl/verilog" \
    "$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/3e37/hdl/axi_vdma_v6_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_vdma_v6_2_9 $vhdlan_opts \
    "$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/3e37/hdl/axi_vdma_v6_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_vdma_0_0/sim/design_1_axi_vdma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/fb8f/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/a07a/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/8ef2/hdl/verilog" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_fifo_w8_d1_A.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_MultiPixStream2AXIvi.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_reg_int_s.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_reg_unsigned_short_s.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgBackground.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgForeground.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternBox.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternCheckerBoa.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternCheckerocq.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternCheckerqcK.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternCheckersc4.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternCheckertde.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternColorBars.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternCrossHa2iS.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternCrossHaDeQ.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternCrossHaEe0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternCrossHair.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternCrossHatch.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternDPBlackWhi.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternDPColorbkb.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternDPColorcud.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternDPColordEe.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternDPColoreOg.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternDPColorfYi.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternDPColorg8j.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternDPColorhbi.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternDPColoribs.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternDPColorjbC.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternDPColorkbM.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternDPColorlbW.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternDPColormb6.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternDPColorncg.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternDPColorRam.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternDPColorSqu.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternHorizontal.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternMask.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternRainbow.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternRainbowvdy.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternSolidBlack.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternSolidBlue.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternSolidBlZio.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternSolidGr0iy.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternSolidGreen.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternSolidRe1iI.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternSolidRed.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternSolidWhite.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternTartanCFfa.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternTartanColo.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternTemporalRa.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternVerticalHo.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternVerticalRa.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternZonePlaMgi.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternZonePlate.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPRBS.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_v_tpg.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_v_tpg_am_addmul_1OgC.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_v_tpg_CTRL_s_axi.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_v_tpg_mac_muladd_Aem.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_v_tpg_mac_muladd_Bew.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_v_tpg_mac_muladd_CeG.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_v_tpg_mac_muladd_Ngs.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_v_tpg_mac_muladd_PgM.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_v_tpg_mac_muladd_yd2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_v_tpg_mac_muladd_zec.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_v_tpg_mul_8ns_6nsxdS.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_v_tpg_mul_8ns_8s_wdI.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_v_tpg_mul_mul_9nsQgW.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternCrossHa0iy.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternCrossHaBew.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternCrossHaCeG.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternSolidBlXh4.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternSolidGrYie.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternSolidReZio.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternTartanCDeQ.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_tpgPatternZonePlaKfY.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_v_tpg_am_addmul_1Mgi.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_v_tpg_mac_muladd_Lf8.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_v_tpg_mac_muladd_wdI.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_v_tpg_mac_muladd_xdS.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/verilog/design_1_v_tpg_0_0_v_tpg_mul_mul_9nsOgC.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_fifo_w8_d1_A.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_MultiPixStream2AXIvi.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_reg_int_s.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_reg_unsigned_short_s.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgBackground.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgForeground.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternBox.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternCheckerBoa.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternCheckerocq.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternCheckerqcK.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternCheckersc4.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternCheckertde.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternColorBars.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternCrossHa2iS.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternCrossHaDeQ.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternCrossHaEe0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternCrossHair.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternCrossHatch.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternDPBlackWhi.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternDPColorbkb.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternDPColorcud.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternDPColordEe.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternDPColoreOg.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternDPColorfYi.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternDPColorg8j.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternDPColorhbi.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternDPColoribs.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternDPColorjbC.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternDPColorkbM.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternDPColorlbW.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternDPColormb6.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternDPColorncg.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternDPColorRam.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternDPColorSqu.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternHorizontal.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternMask.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternRainbow.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternRainbowvdy.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternSolidBlack.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternSolidBlue.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternSolidBlZio.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternSolidGr0iy.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternSolidGreen.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternSolidRe1iI.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternSolidRed.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternSolidWhite.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternTartanCFfa.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternTartanColo.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternTemporalRa.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternVerticalHo.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternVerticalRa.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternZonePlaMgi.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternZonePlate.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPRBS.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_v_tpg.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_v_tpg_am_addmul_1OgC.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_v_tpg_CTRL_s_axi.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_v_tpg_mac_muladd_Aem.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_v_tpg_mac_muladd_Bew.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_v_tpg_mac_muladd_CeG.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_v_tpg_mac_muladd_Ngs.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_v_tpg_mac_muladd_PgM.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_v_tpg_mac_muladd_yd2.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_v_tpg_mac_muladd_zec.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_v_tpg_mul_8ns_6nsxdS.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_v_tpg_mul_8ns_8s_wdI.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_v_tpg_mul_mul_9nsQgW.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternCrossHa0iy.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternCrossHaBew.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternCrossHaCeG.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternSolidBlXh4.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternSolidGrYie.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternSolidReZio.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternTartanCDeQ.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_tpgPatternZonePlaKfY.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_v_tpg_am_addmul_1Mgi.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_v_tpg_mac_muladd_Lf8.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_v_tpg_mac_muladd_wdI.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_v_tpg_mac_muladd_xdS.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/hdl/vhdl/design_1_v_tpg_0_0_v_tpg_mul_mul_9nsOgC.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_tpg_v7_0_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/fb8f/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/a07a/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/8ef2/hdl/verilog" \
    "$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/hdl/v_tpg_v7_0_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/fb8f/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/a07a/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/8ef2/hdl/verilog" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_tpg_0_0/sim/design_1_v_tpg_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_ila_0_0/sim/design_1_ila_0_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_ila_0_1/sim/design_1_ila_0_1.vhd" \
    "$ref_dir/../../../bd/design_1/hdl/design_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_protocol_converter_v2_1_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/fb8f/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/a07a/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/8ef2/hdl/verilog" \
    "$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/4a8b/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/fb8f/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/a07a/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/8ef2/hdl/verilog" \
    "$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/cf3b/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/fb8f/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/a07a/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/8ef2/hdl/verilog" \
    "$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/4a86/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/fb8f/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/a07a/hdl/verilog" +incdir+"$ref_dir/../../../../mpsoc_int.srcs/sources_1/bd/design_1/ipshared/8ef2/hdl/verilog" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_0/sim/design_1_auto_ds_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_1/sim/design_1_auto_ds_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_0/sim/design_1_auto_pc_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_2/sim/design_1_auto_ds_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_3/sim/design_1_auto_ds_3.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_1/sim/design_1_auto_pc_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_4/sim/design_1_auto_ds_4.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_2/sim/design_1_auto_pc_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_5/sim/design_1_auto_ds_5.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_3/sim/design_1_auto_pc_3.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_us_0/sim/design_1_auto_us_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.design_1 xil_defaultlib.glbl -o design_1_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./design_1_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./design_1.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key design_1_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc design_1_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./design_1.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: design_1.sh [-help]\n\
Usage: design_1.sh [-lib_map_path]\n\
Usage: design_1.sh [-reset_run]\n\
Usage: design_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
